name: sign_language_app
description: Application de reconnaissance de langue des signes avec connectivité ESP32.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  camera: ^0.10.5+9
  hand_landmarker: ^2.2.0
  tflite_flutter: ^0.10.1 # Pour exécuter nos modèles convertis

  # Utils
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  translator: ^1.0.4+1

  google_fonts: ^6.2.0
  flutter_animate: ^4.5.2
  percent_indicator: ^4.2.5
  image_picker: ^1.0.8
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.2
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  permission_handler: ^11.3.1
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  
  # Activer les assets
  assets:
    - assets/
    - assets/gestures/
    - assets/model_letters.tflite
    - assets/model_words.tflite
    - assets/model_letters_labels.txt
    - assets/model_words_labels.txt
    - assets/hand_landmarker.task


