name: sign_language_app
description: Application de reconnaissance de langue des signes avec connectivité ESP32.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  # Caméra et Vision
  camera: ^0.10.5+9
  tflite_flutter: ^0.10.1 # Pour exécuter nos modèles convertis

  hand_landmarker: ^0.0.3 

  image_picker: ^1.0.7

  
  # UI Modern
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3 # Pour la barre de progression validation
  
  # Audio / Parole
  flutter_tts: ^3.8.3
  speech_to_text: ^6.6.0
  
  # Connectivité
  http: ^1.2.0
  web_socket_channel: ^2.4.0 # Pour flux ESP32 rapide
  permission_handler: ^11.3.0
  
  # Utils
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  
  # Activer les assets
  assets:
    - assets/
    - assets/gestures/


